server:  
  port: 8088
  connection-timeout: 3000


logging:
  level:
    cn:
      deercare: debug


spring:
  datasource:
       name: mydb
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/crowdfunding?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
       username: root
       password: 12345678 #devops123
       initial-size: 5
       min-idle: 5
       max-active: 20
       # 配置获取连接等待超时的时间
       max-wait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       time-between-eviction-runs-millis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
       min-evictable-idle-time-millis: 300000

#mybatis:
  #type-aliases-package: com.xxx.model #model层
  #mapper-locations: classpath*:mapping/**/*Mapper.xml #mapper的xml

  #configuration:
        #map-underscore-to-camel-case: true #开启驼峰命名功能
        #callSettersOnNulls: true #
mybatis-plus:
  mapper-locations: classpath*:mapping/**/*Mapper.xml
  type-aliases-package: com.deercare.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

schedules:
  # userWechatInfo: 0 */3 * * * ?
  userWechatInfo: 0 0 2 * * ?
  projectPaySuccess: 0 0 12 * * ?
  projectIncome: 0 0 12 * * ?
